language: rust
cache: cargo

sudo: false

os:
    - linux
    - osx

rust:
    - stable
    - beta 
    - nightly

before_script:
    - rustup component add rustfmt

script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo fmt --all -- --check
