language: rust
cache: cargo

os:
- linux
- osx
- windows

rust:
- stable
- beta
- nightly

services:
- docker

before_script:
- rustup component add rustfmt

script:
- cargo build --all --locked --verbose
- cargo test --all --locked --verbose
- |
  if [[ "$TRAVIS_RUST_VERSION" == "stable" ]]; then
    cargo fmt --all -- --check
  fi

after_success: |
  if [ "${TRAVIS_OS_NAME}" == linux ] && [ "${TRAVIS_RUST_VERSION}" == stable ]; then
    docker build -t monolith .
    docker run monolith monolith -V
  fi

jobs:
  allow_failures:
  - rust: nightly
  fast_finish: true
