[package]
name = "monolith"
version = "2.0.13"
authors = [
    "Sunshine <sunshine@uberspace.net>",
    "Mahdi Robatipoor <mahdi.robatipoor@gmail.com>",
]
description = "CLI tool for saving web pages as a single HTML file"

[dependencies]
base64 = "0.10.1"
clap = "2.33.0"
html5ever = "0.24.0"
indicatif = "0.11.0"
lazy_static = "1.3.0"
regex = "1.2.1"
reqwest = "0.9.20"
url = "2.1.0"
