[package]
name = "monolith"
version = "2.4.0"
authors = [
    "Sunshine <sunshine@uberspace.net>",
    "Mahdi Robatipoor <mahdi.robatipoor@gmail.com>",
    "Emmanuel Delaborde <th3rac25@gmail.com>",
    "Emi Simpson <emi@alchemi.dev>",
    "rhysd <lin90162@yahoo.co.jp>",
]
edition = "2018"
description = "CLI tool for saving web pages as a single HTML file"
homepage = "https://github.com/Y2Z/monolith"
repository = "https://github.com/Y2Z/monolith"
readme = "README.md"
keywords = ["web", "http", "html", "download", "command-line"]
categories = ["command-line-utilities", "web-programming"]
include = [
    "src/*.rs",
    "Cargo.toml",
]
license = "Unlicense"
license-file = "LICENSE"

[dependencies]
base64 = "0.13.0"
chrono = "0.4.19" # Used for formatting creation timestamp
clap = "2.33.3"
cssparser = "0.28.0"
html5ever = "0.24.1"
regex = "1.4.2" # Used for parsing srcset
sha2 = "0.9.2" # Used for calculating checksums during integrity checks
url = "2.2.0"

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["default-tls", "blocking", "gzip"]

[dev-dependencies]
assert_cmd = "1.0.2"
tempfile = "3.1.0"
