[package]
name = "monolith"
version = "2.1.2"
edition = "2018"
authors = [
    "Sunshine <sunshine@uberspace.net>",
    "Mahdi Robatipoor <mahdi.robatipoor@gmail.com>",
    "Emmanuel Delaborde <th3rac25@gmail.com>",
    "Emi Simpson <emi@alchemi.dev>",
    "rhysd <lin90162@yahoo.co.jp>",
]
description = "CLI tool for saving web pages as a single HTML file"

[dependencies]
base64 = "0.11.0"
clap = "2.33.0"
html5ever = "0.24.1"
lazy_static = "1.4.0"
regex = "1.3.4"
url = "2.1.1"

[dependencies.reqwest]
version = "0.10.*"
default-features = false
features = ["default-tls", "blocking", "gzip"]
