[package]
name = "monolith"
version = "2.2.7"
edition = "2018"
authors = [
    "Sunshine <sunshine@uberspace.net>",
    "Mahdi Robatipoor <mahdi.robatipoor@gmail.com>",
    "Emmanuel Delaborde <th3rac25@gmail.com>",
    "Emi Simpson <emi@alchemi.dev>",
    "rhysd <lin90162@yahoo.co.jp>",
]
description = "CLI tool for saving web pages as a single HTML file"

[dependencies]
base64 = "0.12.2"
chrono = "0.4.11" # Used to render comments indicating the time the page was saved
clap = "2.33.1"
cssparser = "0.27.2"
html5ever = "0.24.1"
sha2 = "0.9.0" # Used in calculating checksums during integrity checks
url = "2.1.1"

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["default-tls", "blocking", "gzip"]

[dev-dependencies]
assert_cmd = "1.0.1"
tempfile = "3.1.0"
