# Monolith 翻译配置文件示例
# 复制此文件为 translation-config.toml 并根据需要修改

[translation]
# 是否启用翻译功能（命令行参数会覆盖此设置）
enabled = true

# 源语言代码，"auto" 表示自动检测
source_lang = "auto"

# 目标语言代码
target_lang = "zh"

# DeepLX API 地址
# 默认值：本地 DeepLX 服务
# deeplx_api_url = "http://localhost:1188/translate"

# 或者使用远程服务（需要有效的 token）
deeplx_api_url = "https://deepl3.fileaiwork.online/dptrans?token=ej0ab47388ed86e843de9f499e52e6e664ae1m491cad7bf1.bIrYaAAAAAA=.b9c326068ac3c37ff36b8fea77867db51ddf235150945d7ad43472d68581e6c4pd14&newllm=1"

# 每秒最大请求数（避免 API 限制）
max_requests_per_second = 5.0

# 单次翻译的最大文本长度（字符数）
max_text_length = 50000

# 单次请求的最大段落数
max_paragraphs_per_request = 100

# 配置文件说明：
# 1. 此配置文件为可选，如果不存在将使用默认值
# 2. 命令行参数（--target-lang, --translation-api）会覆盖配置文件设置
# 3. 支持的配置文件位置（按优先级排序）：
#    - translation-config.toml
#    - config.toml
#    - .translation-config.toml
#    - ~/.config/monolith/translation.toml
#    - /etc/monolith/translation.toml
