name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        rust:
          - stable
    runs-on: ${{ matrix.os }}

    steps:
    - run: git config --global core.autocrlf false
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --all --locked --verbose
